### ISSUE TITLE
miopen_plugin is missing dependency declarations

### ISSUE THREAD

**Issue by jtiemer** [rocm-arch/tensorflow-rocm#10]
<details>
<summary>miopen_plugin is missing dependency declarations</summary>

```
ERROR: /home/USER/Build/tensorflow-rocm/src/tensorflow-2.3.0-rocm/tensorflow/stream_executor/rocm/BUILD:217:11: undeclared inclusion(s) in rule '//tensorflow/stream_executor/rocm:miopen_plugin':
this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/rocm/rocm_dnn.cc':
  'bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/miopen/miopen.h'
  'bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/miopen/config.h'
  'bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/miopen/export.h'
INFO: Elapsed time: 161,927s, Critical Path: 45,25s
INFO: 225 processes: 225 local.
FAILED: Build did NOT complete successfully

```

</details>

Steps to reproduce: Start clean build via pikaur or makepkg.

<details>
<summary>Successive non-clean builds yield</summary>

```
ERROR: /home/USER/Build/tensorflow-rocm/src/tensorflow-2.3.0-rocm/tensorflow/stream_executor/rocm/BUILD:217:11: C++ compilation of rule '//tensorflow/stream_executor/rocm:miopen_plugin' failed (Exit 1)
tensorflow/stream_executor/rocm/rocm_dnn.cc:23:10: fatal error: rocm/include/miopen/miopen.h: No such file or directory
   23 | #include "rocm/include/miopen/miopen.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ERROR: /home/USER/Build/tensorflow-rocm/src/tensorflow-2.3.0-rocm/tensorflow/python/tools/BUILD:226:10 C++ compilation of rule '//tensorflow/stream_executor/rocm:miopen_plugin' failed (Exit 1)
INFO: Elapsed time: 14,091s, Critical Path: 9,82s
INFO: 27 processes: 27 local.
FAILED: Build did NOT complete successfully
```

</details>

**Comment by acxz** [comment]
Are you on `miopen-hip-3.5.0-5`? I think this is a dup of #7

**Comment by jtiemer** [comment]
I am not sure. It yields the same error, but only on the second non-clean run.
I updated yesterday and am on ```miopen-hip-3.5.0-6``` from the arch4edu repo.

**Comment by acxz** [comment]
Can you post the output of a quick: `ls /opt/rocm/include/miopen`?

**Comment by jtiemer** [comment]
```ls -lh /opt/rocm/include/miopen```
yields

```
lrwxrwxrwx  1 root root   36  7. Aug 21:47 config.h -> ../../miopen/include/miopen/config.h
lrwxrwxrwx  1 root root   36  7. Aug 21:47 export.h -> ../../miopen/include/miopen/export.h
lrwxrwxrwx  1 root root   36  7. Aug 21:47 miopen.h -> ../../miopen/include/miopen/miopen.h
lrwxrwxrwx  1 root root   37  7. Aug 21:47 version.h -> ../../miopen/include/miopen/version.h
```

Note: It only yields this error on the second try to compile _without_ deleting the build directory.

On a clean build it complains about the missing dependency declarations for 

```
bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/miopen/miopen.h
bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/miopen/config.h
bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/miopen/export.h
```

Which are found in 
```home/USER/Build/tensorflow-rocm/src/tensorflow-2.3.0-rocm/bazel-out/…```

Both versions of ```miopen.h``` are 220.5 KiB and identical according to diff.

```pacman -Qo /opt/rocm/include/miopen/miopen.h``` says that it is owned by ```miopen-hip 3.5.0-6``` as expected.

**Comment by jtiemer** [comment]
When trying to reproduce again with a completely clean build, it ended up yielding ```miopen.h: No such file or directory``` so it is most likely indeed a duplicate of #7

**Comment by jtiemer** [comment]
When trying to compile with ```miopen-hip 3.5.0-5``` from AUR, the original error resurfaces. When compiling with ```3.5.0-6``` from arch4edu it's the #7 error. So this seems to be distinct after all.

**Comment by acxz** [comment]
Maybe also remove your bazel cache? `rm -rf ~/.cache/bazel`
Also 3.5.0-5 in the AUR and 3.5.0-6 in the arch4edu should be the exact same PKGBUILD.

**Comment by acxz** [comment]
@jtiemer have you been able to spend more time on this?
`tensorflow-rocm` should be building fine now, (at least builds for me and the arch4edu folks)

**Comment by jtiemer** [comment]
Hey, no, I was traveling over the weekend and had no capacity to try building it. It is compiling now. I will update this posting once it terminates.

Edit: compile successful.

**Comment by jtiemer** [comment]
Okay, I woke up and it terminated successfully. Couldn't check tensorflow gpu availability though as I need to update my BIOS/UEFI first. The AMD random number generator thing from last year seems to be an issue here. I'll do that this evening.

**Comment by jtiemer** [comment]
```tensorflow-rocm``` installs just fine and loads too. It fails when checking GPU availability though. It's not related to this issue. I'm therefore closing this one and opening a new one.
