### ISSUE TITLE
python-past dependency not found in any repo or in AUR

### ISSUE THREAD

**Issue by DarjanKrijan** [rocm-arch/tensorflow-rocm#18]
This builds for now but the python package won't install because of a missing ```python-past``` dependency.

Installs when I remove that dependency but not sure if it breaks some functionality.
Can't test much as miopen-hip is currently at 3.8 and it's falling back to CPU as it doesn't find ```libamdhip64.so.3```.

**Comment by nquest** [comment]
past in now part of future. Updated PKGBUILD in PR #19

**Comment by acxz** [comment]
leaving this open as patched until upstream community/tensorflow pkgbuild doesn't have the python-past fix.

**Comment by nquest** [comment]
upstream PKGBUILD depends on python-pasta. Trying to build with it.

**Comment by acxz** [comment]
Seems like `python-past` was a typo of `python-pasta`. Closed with  b61b740
