### ISSUE TITLE
Should be built against Python 3.8

### ISSUE THREAD

**Issue by CyberShadow** [rocm-arch/tensorflow-rocm#23]
Python 3.9 is not supported by upstream yet:

https://github.com/tensorflow/tensorflow/issues/44485

This causes problems such as:

https://stackoverflow.com/questions/66141547/notimplementederror-cannot-convert-a-symbolic-tensor-to-a-numpy-array

So, for example, there is no way to use Keras LSTM layers with this package right now.

I don't know how feasible it is, but if possible, the Python packages have to be built against Python versions supported by them.

**Comment by astrowave** [comment]
This issue can be closed as TF has supported python 3.9 since version 2.5.0

**Comment by CyberShadow** [comment]
> I don't know how feasible it is, but if possible, the Python packages have to be built against Python versions supported by them.

This is maybe still true in general. Unless something fundamental changed, the same problems will likely happen with Python 3.9/3.10.

**Comment by acxz** [comment]
@CyberShadow this PKGBUILD is based off the PKGBUILD for the tensorflow build from the official archlinux builds: https://archlinux.org/packages/community/x86_64/tensorflow/

Only the required changes to get the ROCm build to work are added to this PKGBUILD. Eventually the goal is to merge the changes in this PKGBUILD with the official one. In lieu of that, we will not build against specific python versions unless the official one does.

**Comment by CyberShadow** [comment]
Good to know. I didn't think to check at the time if the problem also applies to the `community` package. If I did, I would have filed the bug against the `community` package instead.

Though, note that for this to be fixed in the `community` package, `python38` would have to be moved to `community` too. This condition does not hold for this package, as it is in AUR.
