### ISSUE TITLE
Cant import module

### ISSUE THREAD

**Issue by RavenOchlich** [rocm-arch/tensorflow-rocm#24]
Are there any additional steps needed after installing the package? I can't import the tensorflow module after installing the tensorflow-rocm module.

**Comment by acxz** [comment]
Can you post the commands you are running and any error message that pops up?

**Comment by RavenOchlich** [comment]
rwo@main ~ [SIGINT]> yay -S tensorflow-rocm
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  tensorflow-rocm-2.4.0-4

  1 tensorflow-rocm                          (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: PKGBUILD up to date, Skipping (1/1): tensorflow-rocm
  1 tensorflow-rocm                          (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: (1/1) Parsing SRCINFO: tensorflow-rocm
==> Making package: tensorflow-rocm 2.4.0-4 (Mi 24 Mär 2021 23:32:03 CET)
==> Retrieving sources...
  -> Found tensorflow-rocm-2.4.0.tar.gz
  -> Found fix-h5py3.0.patch
  -> Found build-against-actual-mkl.patch
==> Validating source files with sha512sums...
    tensorflow-rocm-2.4.0.tar.gz ... Passed
    fix-h5py3.0.patch ... Passed
    build-against-actual-mkl.patch ... Passed
==> Making package: tensorflow-rocm 2.4.0-4 (Mi 24 Mär 2021 23:32:07 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found tensorflow-rocm-2.4.0.tar.gz
  -> Found fix-h5py3.0.patch
  -> Found build-against-actual-mkl.patch
==> Validating source files with sha512sums...
    tensorflow-rocm-2.4.0.tar.gz ... Passed
    fix-h5py3.0.patch ... Passed
    build-against-actual-mkl.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting tensorflow-rocm-2.4.0.tar.gz with bsdtar
==> Starting prepare()...
patching file tensorflow/python/keras/saving/hdf5_format.py
==> Sources are ready.
==> Making package: tensorflow-rocm 2.4.0-4 (Mi 24 Mär 2021 23:32:19 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Sources are ready.
 -> tensorflow-rocm-2.4.0-4 already made -- skipping build
[sudo] password for rwo: 
loading packages...
warning: tensorflow-rocm-2.4.0-4 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) tensorflow-rocm-2.4.0-4

Total Installed Size:  1733,95 MiB
Net Upgrade Size:         0,00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [####################] 100%
(1/1) checking package integrity                   [####################] 100%
(1/1) loading package files                        [####################] 100%
(1/1) checking for file conflicts                  [####################] 100%
(1/1) checking available disk space                [####################] 100%
:: Processing package changes...
(1/1) reinstalling tensorflow-rocm                 [####################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
rwo@main ~> python
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
>>>

**Comment by acxz** [comment]
Closing this issue as quite stale and the answer could be a broken build, which is currently a work in progress. Sorry @RavenOchlich
