### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by tallero** [rocm-arch/tensorflow-rocm#27]
Here is the [makepkg.log](https://github.com/rocm-arch/tensorflow-rocm/files/6682684/makepkg.log).

**Comment by CyberShadow** [comment]
A relevant part of the log:

`ERROR: /home/user/.cache/bazel/_bazel_user/21151a2a968d617c618f2cfdc68e32ca/external/mkl_dnn_v1/BUILD.bazel:120:11: Compiling src/common/primitive_cache.cpp failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer ... (remaining 71 argument(s) skipped)`

`external/mkl_dnn_v1/src/common/primitive_cache.cpp: In member function 'virtual void dnnl::impl::lru_primitive_cache_t::update_entry(const key_t&, const dnnl::impl::primitive_desc_t*)':`

`external/mkl_dnn_v1/src/common/primitive_cache.cpp:155:60: error: no match for 'operator!=' (operand types are 'const std::thread::id' and 'const std::thread::id')`

**Comment by surak** [comment]
Did you solve it?

**Comment by tallero** [comment]
@surak dealing with worse [problems](https://gitlab.freedesktop.org/drm/amd/-/issues/1803).

**Comment by acxz** [comment]
Closing this issue as a stale build issue.
If you have further issues please open up another issue.
Sorry @tallero @CyberShadow @surak
