### ISSUE TITLE
Tensorflow 2.6.0 build failure due to segfault

### ISSUE THREAD

**Issue by afzalarsalan** [rocm-arch/tensorflow-rocm#33]
The build for Tensorflow 2.6.0 fails with the following

compile tensorflow/core/kernels/mlir_generated/atan2_gpu_f16_f16_kernel_generator_kernel.o failed: (Segmentation fault).

This happens towards the end of the compilation phase

**Comment by justinkb** [comment]
I bumped it to 2.6.2 and it segfaulted on tensorflow/core/kernels/mlir_generated/is_finite_gpu_f16_i1_kernel_generator_kernel.o for me, likely the very same issue

edit: see https://github.com/tensorflow/tensorflow/issues/50345

**Comment by riaqn** [comment]
@justinkb does it work for you? I use the workaround mentioned in the link and it doesn't solve the problem.

**Comment by acxz** [comment]
Can you guys update your error now that the package has been updated to `2.8.0`?

**Comment by mindless728** [comment]
Currently there are two issues (as of today)
1. The bazel install from arch is version 5.1.0 and the tensorflow build requires < 5.0.0
2. Can't download the link for tensorflow, maybe it's wrong?

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/c3e082762b7664bbc7ffd2c39e86464928e27c0c.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

**Comment by acxz** [comment]
Closing this issue as a stale build issue.
If you have further issues please open up another issue.
Sorry @afzalarsalan @justinkb @riaqn
