### ISSUE TITLE
Package no longer builds due to Bazel version

### ISSUE THREAD

**Issue by mikesbytes** [rocm-arch/tensorflow-rocm#38]
When building the package I receive the following error:

```
You have bazel 5.1.0 installed.
Please downgrade your bazel installation to version 4.99.0 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.
```

There's no `bazel4` package to easily downgrade so I figured it warranted filing an issue since this currently can't be built without some manual work.

**Comment by acxz** [comment]
This is resolved with the update to `tensorflow-rocm-2.9.1`, which does not require bazel < 4.
