### ISSUE TITLE
Maximum GCC version

### ISSUE THREAD

**Issue by bulvara** [rocm-arch/tensorflow-rocm#39]
Hi Akash,

this is not a bug report, just a question: What is the highest working GCC version for you?

Kind regards,
bulvara

**Comment by acxz** [comment]
I actually haven't tried compiling this project in a long time, as my current efforts are focusing on the pytorch package.

The last time I did successfully compile this project was gcc 10 i believe?
Although I don't see why it won't work on the current gcc 12.
