### ISSUE TITLE
v2.9.1 Building fails to Error in genrule

### ISSUE THREAD

**Issue by Keridos** [rocm-arch/tensorflow-rocm#42]
See the log here: https://gist.github.com/Keridos/3bd548946e8458dc8c06c604ea21e373

**Comment by petronny** [comment]
I confirm this issue. https://github.com/arch4edu/cactus/runs/7482159879?check_suite_focus=true

**Comment by yshui** [comment]
Upstream bug: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1639

**Comment by acxz** [comment]
Closing due to outdated error

Also upstream for this repo is https://github.com/tensorflow/tensorflow
