### ISSUE TITLE
Cannot resolve dependencies

### ISSUE THREAD

**Issue by charlescoult** [rocm-arch/tensorflow-rocm#46]
```
warning: cannot resolve "hip-rocclr", a dependency of "rocm-dev"
warning: cannot resolve "llvm-amdgpu", a dependency of "rocm-dev"
warning: cannot resolve "rocm-smi-lib64", a dependency of "rocm-dev"
warning: cannot resolve "rocm", a dependency of "python-tensorflow-rocm"
warning: cannot resolve "rocm-libs", a dependency of "python-tensorflow-rocm"
```
Not sure what is causing this exactly - I'm still pretty new to all this, if that wasn't obvious.

**Comment by BishopWolf** [comment]
You have a version conflict in rocm (the different packages has different versions).
If you are not developping for rocm, you are then a simple rocm user, so you better use opencl-amd package.
If you need the dev part then install opencl-amd-dev. 
You shall remove individual rocm packages before installing the opencl ones

**Comment by acxz** [comment]
My guess is that you tried to install `tensorflow-rocm` while some of the `rocm` stack was in limbo between `AUR` and `[community]`.

Can you go ahead and try again now that the rocm package are more stable?

For now I'll close this issue, if you are still having this problem feel free to comment.
