### ISSUE TITLE
Unable to make Package

### ISSUE THREAD

**Issue by ingandresgamer** [rocm-arch/tensorflow-rocm#61]
Im Currently tring to install de pagage but i get an error .. it seems to have conflict with opncl-amd

`[andres@archlinux tensorflow-rocm]$ makepkg -si PKGBUILD 
==> Making package: tensorflow-rocm 2.12.0-3 (Thu 03 Aug 2023 12:09:23 PM -05)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
[sudo] password for andres: 
resolving dependencies...
looking for conflicting packages...

Packages (44) blas-3.11.0-2  cblas-3.11.0-2  composable-kernel-5.5.1-2
              gcc12-libs-12.3.0-2  hdf5-1.14.1-1  hipblas-5.6.0-1
              hipcub-5.6.0-1  hipfft-5.6.0-1  hipsolver-5.6.0-1
              hipsparse-5.6.0-1  lapack-3.11.0-2  libaec-1.0.6-1  liblzf-3.6-4
              python-attrs-22.2.0-3  python-cffi-1.15.1-3
              python-cryptography-41.0.2-1  python-idna-3.4-3
              python-ply-3.11-12  python-pycparser-2.21-5
              python-urllib3-1.26.15-1  rocalution-5.6.0-1  rocblas-5.6.0-1
              rocfft-5.6.0-1  rocm-hip-libraries-5.6.0-1  rocm-llvm-5.6.0-1
              rocprim-5.6.0-1  rocrand-5.6.0-1  rocsolver-5.6.0-1
              rocsparse-5.6.0-1  rocthrust-5.6.0-1  cython-3.0.0-1
              gcc12-12.3.0-2  miopen-hip-5.6.0-1  patchelf-0.18.0-1
              python-h5py-3.9.0-1  python-installer-0.7.0-3
              python-keras-applications-1.0.8-9
              python-keras-preprocessing-1.1.2-7  python-numpy-1.25.1-1
              python-pip-23.2.1-1  python-requests-2.28.2-4
              python-wheel-0.40.0-3  rccl-5.6.0-1  rocm-hip-sdk-5.6.0-1

Total Installed Size:  18282.06 MiB

:: Proceed with installation? [Y/n] Y
(44/44) checking keys in keyring                                                                                                               [#######################################################################################] 100%
(44/44) checking package integrity                                                                                                             [#######################################################################################] 100%
(44/44) loading package files                                                                                                                  [#######################################################################################] 100%
(44/44) checking for file conflicts                                                                                                            [#######################################################################################] 100%
error: failed to commit transaction (conflicting files)
rocblas: /opt/rocm exists in filesystem (owned by opencl-amd)
rocprim: /opt/rocm exists in filesystem (owned by opencl-amd)
rocsparse: /opt/rocm exists in filesystem (owned by opencl-amd)
rocsolver: /opt/rocm exists in filesystem (owned by opencl-amd)
hipblas: /opt/rocm exists in filesystem (owned by opencl-amd)
rocfft: /opt/rocm exists in filesystem (owned by opencl-amd)
hipfft: /opt/rocm exists in filesystem (owned by opencl-amd)
hipsparse: /opt/rocm exists in filesystem (owned by opencl-amd)
hipsolver: /opt/rocm exists in filesystem (owned by opencl-amd)
rccl: /opt/rocm exists in filesystem (owned by opencl-amd)
rocrand: /opt/rocm exists in filesystem (owned by opencl-amd)
rocalution: /opt/rocm exists in filesystem (owned by opencl-amd)
rocm-llvm: /opt/rocm exists in filesystem (owned by opencl-amd)
hipcub: /opt/rocm exists in filesystem (owned by opencl-amd)
composable-kernel: /opt/rocm exists in filesystem (owned by opencl-amd)
miopen-hip: /opt/rocm exists in filesystem (owned by opencl-amd)
rocthrust: /opt/rocm exists in filesystem (owned by opencl-amd)
Errors occurred, no packages were upgraded.
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> python-numpy
  -> rocm-hip-sdk
  -> rccl
  -> miopen
  -> python-pip
  -> python-wheel
  -> python-installer
  -> python-h5py
  -> python-keras-applications
  -> python-keras-preprocessing
  -> cython
  -> patchelf
  -> python-requests
  -> gcc12
==> ERROR: Could not resolve all dependencies.
`

**Comment by mpeschel10** [comment]
If your graphics card is new enough, you may be able to uninstall `opencl-amd` and use the `extra` build of the hip stack.
You can check your architecture by running `/opt/rocm/bin/rocminfo | grep gfx`. Mine is gfx1031:
```sh
[mpeschel@suzerain ~]$ /opt/rocm/bin/rocminfo | grep gfx
  Name:                    gfx1031                            
      Name:                    amdgcn-amd-amdhsa--gfx1031
```
If your architecture is in the following list, it is probably supported by the `extra` repository:
```
gfx900
gfx906
gfx908
gfx90a
gfx1030
gfx1100
```
( Copied from the `GPU_DEVICE_TARGETS` line of the [tensorflow-upstream build-environment dockerfile](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/Dockerfile.rocm) )

**Comment by acxz** [comment]
@ingandresgamer `opencl-amd` from the aur and the rocm packages from `extra` conflict one another. This package depends on the rocm packages from `extra`, hence, you'll have to remove `opencl-amd` to use this package.
